### ISSUE TITLE
Contact Assemblée

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/mapHemicycle#1]
Salut @Sav10,

On a été contactés par l'Assemblée qui souhaiterait développer quelque chose de semblable en interne, il faudrait qu'on t'implique :)

Tu peux nous faire un mail à contact@regardscitoyens.org ?

**Comment by Sav10** [comment]
Bonjour à tous,

Avec grand plaisir !

D'autant plus que j'ai un peu avancé sur le projet :
- J'ai tabularisé (csv à présent) et largement réduit en taille le json
"scrutins" ce qui a eu pour effet de réduire significativement sa taille
- J'ai inséré un slider et un select (moche pour l'instant) permettant de
visualiser tous les scrutins solennels de la législature.


A bientôt


Savinen

Le 4 décembre 2016 à 22:38, Benjamin Ooghe-Tabanou <notifications@github.com

**Comment by boogheta** [comment]
Salut, je voulais merger tes ajouts du coup mais je n'ai pas l'impression que tu aies commité le slider et le select si ?

**Comment by Sav10** [comment]
Si, j'ai créé une branche, slider-menu, que j'ai commité

2016-12-05 12:37 GMT+01:00 Benjamin Ooghe-Tabanou <notifications@github.com>
:

**Comment by Sav10** [comment]
Attends, je n'ai pas commité l'index

2016-12-05 12:37 GMT+01:00 Benjamin Ooghe-Tabanou <notifications@github.com>
:

**Comment by boogheta** [comment]
oui j'ai bien vu la branche :)

**Comment by Sav10** [comment]
C'est fait

2016-12-05 12:37 GMT+01:00 Benjamin Ooghe-Tabanou <notifications@github.com>
:

**Comment by Sav10** [comment]
Tu n'as pas encore mergé ?

2016-12-05 12:46 GMT+01:00 Benjamin Ooghe-Tabanou <notifications@github.com>
:

**Comment by boogheta** [comment]
je viens de le faire, j'attendais le commit manquant :)
